import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

type Repository = {
  id: number;
  name: string;
  full_name: string;
};

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  authors: [{ name: "oeyoews", url: "https://github.com/oeyoews/oeyoews" }],
  keywords: "learning",
  bookmarks: "Test",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const res = await fetch("https://api.github.com/repos/vercel/next.js", {
    cache: "no-store",
  });
  const data: Repository = await res.json();
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 className="font-bold m-1">{data.full_name}</h1>
        {children}
      </body>
    </html>
  );
}
